spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost:1521/daremall;MODE=MySQL;
    #url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL;
    #url : jdbc:mysql//jsw5258@35.203.149.95:3306/daremall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #       show_sql: true sout로 찍는거라 logger로 찍어야 함
        format_sql: true
        default_batch_fetch_size: 100
  #mvc:
    #static-path-pattern: /webapp/**
    generate-ddl: false
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # values를 보여줌