spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    #url: jdbc:h2:tcp://localhost:1521/daremall;MODE=MySQL;
    #username: dare
    #password: Dking81$
    #driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://35.203.149.95:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    #username: dare
    #password: Dking81$
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8 #for test
    username: root
    password: Dking81$

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #       show_sql: true sout로 찍는거라 logger로 찍어야 함
        format_sql: true
        default_batch_fetch_size: 100
  #mvc:
    #static-path-pattern: /webapp/**
    generate-ddl: false
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # values를 보여줌